### ISSUE TITLE
支持这样的 URL 吗？

### ISSUE THREAD

**Issue by justqyx** [nimojs/fms-demo#1]
你好，我想问下，可以这么用么？

```js
fms.ajax({
    title: "post",
    type: 'GET',
    url: '/posts/:id',
    res: {
        ok: {
        }
    }
})
```

**Comment by nimojs** [comment]
目前没有，今天刚好在要做这块
你觉得 restful 的文档生成可以跟现在AJAX的文档生成一样么。

**Comment by justqyx** [comment]
文档倒不是我最关心的，我最关心的是 url 配置项的表达能力，能否满足 RESTful 类型的接口。

**Comment by nimojs** [comment]
:ok_hand: 请关注 https://github.com/nimojs/fms/  今天我处理号了 RESTful 的支持后 push 上去

**Comment by justqyx** [comment]
@nimojs 哈哈，感谢 & 期待

**Comment by nimojs** [comment]
请更新最新版 fms,现已支持 RESTful
```
fms.ajax({
    title: "RESTful API",
    type: 'get',
    url: '/user/:id',
    res: {
        ok: {
            status: "success",
            msg: "GET success"
        },
        fn: function (req, res) {
            res.send(req.params['id'])
        }
    }
})
```

有任何问题欢迎在 http://github.com/nimojs/fms 中提交 [issues](https://github.com/nimojs/fms/issues/new)

**Comment by justqyx** [comment]
@nimojs 看到了，感谢，已经用上了

```js
$.ajax({
    title: '测试 RESTFUL',
    type: 'get',
    dataType: 'json',
    url: '/books/:id',
    res: {
        ok: false,
        err: false,
        fn: function(request, response) {
            return {
                a: '123',
                params: request.params
            }
        }
    }
});
```

就是用着挺麻烦，因为我的需求更加简单一些，我所期待的是

```js
fms.get('/users/:id', function(request, response) {
  var staff = {}; // 构造要的数据
  return {
    staff: staff
  };
})
```

甚至这样

```js
fms.get({
  url: '/users/:id',
  response: { // 同时也支持传 function，配合 mock.js 可以构造更好的数据
  }
})
```

**Comment by nimojs** [comment]
http://fmsjs.org/ajax.html#res
```js
fms.get({
  url: '/users/:id',
  res: {
     ok: function (req, res) {

   }
  }
})
```
支持的 。res 里面的参数可以是 对象 数组 字符串 函数，函数的 req res 是express的 req res

**Comment by nimojs** [comment]
对于API易用性我考虑可以实现如下API：
```js
fms.get('/user/:id').ok(function(req, res){
   return req.query.name
})
// 等同于
fms.ajax({
   type: 'get',
   url: "/user/:id",
  res: {
    ok : function(){...}
  }
})
```
你觉得如何？

**Comment by justqyx** [comment]
@nimojs 这个好 !!!

```js
fms.get('/user/:id').ok(function(req, res){
   return req.query.name
})
```

**Comment by nimojs** [comment]
@justqyx 
好的，我晚上回家加上这个语法。并附上说明。因为应该默认支持 .ok .err 因为这两个是在 此处配置的 https://github.com/nimojs/fms/blob/827c9294788cf003e13fa6dbde4b193fc3be602f/lib/config.js#L37-L45。
如果$.run(settings) 配置了其他的 res 就支持其他的res

**Comment by nimojs** [comment]
@justqyx 

请下载最新的 fms

## 链式调用

你还可以使用类似 jQuery 链式调用语法

```js
fms.get('/fms.get/', {title: "链式调用"}).ok({
    msg: "ok"
}).err({
    meg: "err"
})
```
`{title: "链式调用"}` 非必填

以上代码等同于
```js
fms.ajax({
    title: '链式调用',
    type: 'get',
    url: '/fms.get/',
    res: {
        ok: {
            msg: "ok"
        },
        err: {
            msg: "err"
        }
    }
})
```

虽然 `fms.get(url, settings)` `fms.post` `fms.put` `fms.delete` 链式语法中可省略 `settings`，但最好在 settins 中增加 `title` 和 `request` 。这样能生成更详细的文档。

**Comment by justqyx** [comment]
@nimojs 好的，感谢! 用上了。

**Comment by nimojs** [comment]
后续有任何问题欢迎在 http://github.com/nimojs/fms 中提交 issues

**Comment by nimojs** [comment]
@justqyx 

> fms在 [0.0.23](https://github.com/nimojs/fms/releases/tag/0.0.23) 以上版本 内置了 [Mockjs](http://mockjs.com/#Mock.Random) 和 [chancejs](http://chancejs.com/)
通过 `fms.chance` `fms.Mock` `fms.Random` 使用。（`fms.Random` = `fms.Mock.Random`）
